Add banner
osmosis-labs/osmosis-frontend pull request #1284
Opened 2023-01-31 03:03 UTC by jonator

Closes #1281

2023-01-31 03:04 UTC, sunnya97 commented
Task linked: [CU-862j31xqv Banner - FE Dev](https://app.clickup.com/t/862j31xqv)

2023-02-04 01:50 UTC, JoseRFelix requested changes
Looks good! left some minor comments

2023-02-04 01:50 UTC, JoseRFelix commented on packages/web/components/navbar/index.tsx
> +        {link && (
```suggestion
        {Boolean(link) && (
```

2023-02-04 01:50 UTC, JoseRFelix commented on packages/web/components/navbar/index.tsx
> +            />
We could use the Icon component here

2023-02-04 01:50 UTC, JoseRFelix commented on packages/web/components/navbar/index.tsx
> +          />
Same as above

2023-02-04 01:50 UTC, JoseRFelix commented on packages/web/public/icons/arrow-right-small.svg
> +</svg>
We should add this to the sprites.svg

2023-02-04 01:50 UTC, JoseRFelix commented on packages/web/public/icons/close-small.svg
> +</svg>
Same as above

2023-02-04 08:01 UTC, JoseRFelix approved these changes

2023-02-04 08:01 UTC, JoseRFelix commented on packages/web/components/navbar/index.tsx
> +        </button>
This is minor, but I just noticed that we could use the `IconButton` component

2023-02-06 18:46 UTC, merged