feat: Overwrite address to Connected ICNS Name
osmosis-labs/osmosis-frontend pull request #1285
Opened 2023-01-31 04:28 UTC by JoseRFelix

2023-01-31 04:59 UTC, sunnya97 commented
Task linked: [CU-862j31wrd Design updates for bridging UI](https://app.clickup.com/t/862j31wrd)

2023-01-31 07:04 UTC, sunnya97 commented
Task linked: [CU-8669bgure ICNS Frontend - FE Dev](https://app.clickup.com/t/8669bgure)

2023-01-31 07:07 UTC, jonator requested changes
Let's not forget the withdraw case as well.

2023-01-31 16:26 UTC, JoseRFelix commented on packages/web/hooks/use-address-icns-name.ts
> +export function useAddressICNSName(bech32Address: string) {
You're right. Now taking a second look, it's very shallow. Will fix

2023-02-01 03:47 UTC, jonator approved these changes

2023-02-01 03:47 UTC, merged