Bridge native ETH
osmosis-labs/osmosis-frontend pull request #1331
Opened 2023-02-14 18:58 UTC by jonator

Closes #920 

Starting with just ETH for now. Like with the prior integration @JeremyParish69 can add config for other wrapped tokens async later.

For Axelar wrapped assets:
* Adds config to specify a wrapped equivalent Axelar asset
* Rebrands the asset to appear to be the native asset (even though it's the axlWrapped version under the hood). This is completely abstracted away from the user.
  * Should we change the token icons to be closer to the canonical native icon? @JeremyParish69 
* Adds a toggle for depositing or withdrawing the wrapped equivalent.

Test
* Axelar deposit/withdraw ETH (and WETH)
* Axelar deposit withdraw non-wrapped asset
* Connecting/disconnecting Metamask. Also ensure

2023-02-14 19:18 UTC, victortokaito commented
@jonator Looks good. Btw Jose said you have vercel team access––can you add access to vercel for leaving comments?

2023-02-14 19:42 UTC, JeremyParish69 commented
@jonator ,

Yes, I'll be able to update the other 'secretly' wrapped tokens async.

Regarding the token logos, they should already be of the native unwrapped version. (e.g., how AVAX is white on red (native) and not black on white (wrapped)). I suppose one could argue that ETH's logo should be blue on transparent instead of black/grey on white , but I also think the current is also an equally valid logo for the native token. Can you list which ones you're talking about?

2023-02-14 21:05 UTC, jonator commented
@JeremyParish69 OK I think the logos are fine.

2023-02-15 05:08 UTC, JoseRFelix requested changes
I think we have to merge with `stage`. I see some bug fixes have regressed

2023-02-15 05:08 UTC, JoseRFelix commented on .eslintrc.base.js
> -    "simple-import-sort/exports": "error",
Is this intended? Don't we want to sort imports on our packages?

2023-02-15 05:08 UTC, JoseRFelix commented on package.json
> -    "eslint-plugin-simple-import-sort": "^10.0.0"
Same question as above

2023-02-15 05:08 UTC, JoseRFelix commented on packages/pools/src/errors.ts
> -    Object.setPrototypeOf(this, NotEnoughLiquidityError.prototype);
This should still be 

`Object.setPrototypeOf(this, NotEnoughLiquidityError.prototype);`

Otherwise prototype will not match.

2023-02-15 05:08 UTC, JoseRFelix commented on packages/stores/src/account/index.ts
> +import { BondStatus } from "@keplr-wallet/stores/build/query/cosmos/staking/types";
I see we have some regressions here. Perhaps we have to merge from `stage`?

2023-02-15 05:08 UTC, JoseRFelix commented on packages/stores/src/bridge-history/index.ts
> -  reason?: TxReason;
Same here

2023-02-16 15:31 UTC, jonator commented
Waiting on further design review

2023-02-17 04:15 UTC, sunnya97 commented on packages/web/integrations/axelar/source-chain-config.ts
> +        wrapDenom: "wETH",
```suggestion
        wrapDenom: "WETH",
```

2023-02-17 04:15 UTC, sunnya97 commented on packages/web/integrations/axelar/source-chain-config.ts
> +        wrapDenom: "wGLMR",
```suggestion
        wrapDenom: "WGLMR",
```

2023-02-17 04:15 UTC, sunnya97 commented on packages/web/integrations/axelar/source-chain-config.ts
> +        wrapDenom: "wMATIC",
```suggestion
        wrapDenom: "WMATIC",
```

2023-02-17 04:15 UTC, sunnya97 commented on packages/web/integrations/axelar/source-chain-config.ts
> +        wrapDenom: "wAVAX",
```suggestion
        wrapDenom: "WAVAX",
```

2023-02-17 04:15 UTC, sunnya97 commented on packages/web/integrations/axelar/source-chain-config.ts
> +        wrapDenom: "wFTM",
```suggestion
        wrapDenom: "WFTM",
```

2023-02-17 04:21 UTC, sunnya97 commented on packages/web/integrations/axelar/source-chain-config.ts
> +        wrapDenom: "wBNB",
```suggestion
        wrapDenom: "WBNB",
```

2023-02-17 04:22 UTC, sunnya97 commented on packages/web/integrations/axelar/types.ts
> +   *  i.e. ETH for wETH, BNB for wBNB, etc.
```suggestion
   *  i.e. ETH for WETH, BNB for WBNB, etc.
```

2023-02-17 04:25 UTC, sunnya97 commented on packages/web/localizations/en.json
> +      "useWrappedDeposit": "Deposit {wrapDenom} on satellite.money",
```suggestion
      "useWrappedDeposit": "Deposit {wrapDenom} on Satellite",
```

2023-02-17 04:25 UTC, sunnya97 commented on packages/web/localizations/en.json
> +      "useWrappedWithdraw": "Withdraw {wrapDenom} from satellite.money",
```suggestion
      "useWrappedWithdraw": "Withdraw {wrapDenom} from Satellite",
```

2023-02-17 04:27 UTC, sunnya97 commented on packages/web/localizations/en.json
> +      "useWrappedWithdraw": "Withdraw {wrapDenom} from satellite.money",
```suggestion
      "useWrappedDeposit": "Deposit {wrapDenom} with Satellite",
      "useWrappedWithdraw": "Withdraw {wrapDenom} with Satellite",
```

2023-02-17 04:28 UTC, sunnya97 commented on packages/web/localizations/es.json
> +      "useWrappedWithdraw": "Retirar {wrapDenom} de satellite.money",
```suggestion
      "useWrappedDeposit": "Deposite {wrapDenom} con Satellite",
      "useWrappedWithdraw": "Retirar {wrapDenom} con Satellite",
```

2023-02-17 04:28 UTC, sunnya97 commented on packages/web/localizations/fr.json
> +      "useWrappedWithdraw": "Retirer {wrapDenom} de satellite.money",
```suggestion
      "useWrappedDeposit": "Déposez {wrapDenom} avec Satellite",
      "useWrappedWithdraw": "Retirer {wrapDenom} avec Satellite",
```

2023-02-17 04:30 UTC, sunnya97 commented on packages/web/localizations/ko.json
> +      "useWrappedWithdraw": "satellite.money에서 {wrapDenom} 인출",
```suggestion
      "useWrappedDeposit": "Satellite에 {wrapDenom} 입금",
      "useWrappedWithdraw": "Satellite에서 {wrapDenom} 인출",
```

2023-02-17 04:30 UTC, sunnya97 commented on packages/web/localizations/pl.json
> +      "useWrappedWithdraw": "Wypłać {wrapDenom} z satellite.money",
```suggestion
      "useWrappedDeposit": "Wpłać {wrapDenom} na Satellite",
      "useWrappedWithdraw": "Wypłać {wrapDenom} z Satellite",
```

2023-02-17 04:30 UTC, sunnya97 commented on packages/web/localizations/pt-br.json
> +      "useWrappedWithdraw": "Retirar {wrapDenom} de satellite.money",
```suggestion
      "useWrappedDeposit": "Deposite {wrapDenom} em Satellite",
      "useWrappedWithdraw": "Retirar {wrapDenom} de Satellite",
```

2023-02-17 04:31 UTC, sunnya97 commented on packages/web/localizations/ro.json
> +      "useWrappedWithdraw": "Retrageți {wrapDenom} din satellite.money",
```suggestion
      "useWrappedDeposit": "Depuneți {wrapDenom} pe Satellite",
      "useWrappedWithdraw": "Retrageți {wrapDenom} din Satellite",
```

2023-02-17 04:31 UTC, sunnya97 commented on packages/web/localizations/tr.json
> +      "useWrappedWithdraw": "{wrapDenom}'e satellite.money'den çekin",
```suggestion
      "useWrappedDeposit": "Satellite'e {wrapDenom} yatırın",
      "useWrappedWithdraw": "{wrapDenom}'e Satellite'den çekin",
```

2023-02-17 04:33 UTC, sunnya97 commented on packages/web/localizations/zh-cn.json
> +      "useWrappedWithdraw": "从 satellite.money 中提取 {wrapDenom}",
```suggestion
      "useWrappedDeposit": "在 Satellite 上存入 {wrapDenom}",
      "useWrappedWithdraw": "从 Satellite 中提取 {wrapDenom}",
```

2023-02-17 04:33 UTC, sunnya97 commented on packages/web/localizations/zh-hk.json
> +      "useWrappedWithdraw": "從 satellite.money 中提取 {wrapDenom}",
```suggestion
      "useWrappedDeposit": "在 Satellite 上存入 {wrapDenom}",
      "useWrappedWithdraw": "從 Satellite 中提取 {wrapDenom}",
```

2023-02-17 04:33 UTC, sunnya97 commented on packages/web/localizations/zh-tw.json
> +      "useWrappedWithdraw": "從衛星中選取{wrapDenom} sattelite.money",
```suggestion
      "useWrappedDeposit": "將{wrapDenom}存入Satellite",
      "useWrappedWithdraw": "從衛星中選取{wrapDenom} Satellite",
```

2023-02-17 04:59 UTC, sunnya97 commented
The new unwrapped deposits get stuck on "Pending" in the transfer history table.

<img width="1220" alt="CleanShot 2023-02-16 at 23 57 01@2x" src="https://user-images.githubusercontent.com/979241/219553134-10e26cb4-509d-4f1d-9813-f11731d4eef7.png">

Doesn't seem to be the case on the current live site:
<img width="1113" alt="CleanShot 2023-02-16 at 23 57 07@2x" src="https://user-images.githubusercontent.com/979241/219553280-967bcb9c-9c59-4b76-87af-bed4358f5ed7.png">

2023-02-17 23:49 UTC, sunnya97 commented
When trying to deposit all assets, it doesn't account for gas fees, leaving not enough funds to pay gas.

<img width="358" alt="CleanShot 2023-02-17 at 18 48 48@2x" src="https://user-images.githubusercontent.com/979241/219817806-38ff3ecf-c509-4129-84b6-be9267b891a5.png">

2023-02-21 17:41 UTC, jonator commented
- [ ] Update to match new [design](https://www.figma.com/file/qze5yJO9TEw7vysInR07Ui/Bridge-Integration?node-id=2528%3A114654&t=MhhUiEltkvOMVg6U-4)
- [ ] Fix gas adjustment (see Axelar satellite frontend code)

2023-02-23 14:36 UTC, jonator commented
Fixes 
- [ ] Selecting max for amounts smaller than gas cost, gets set as negative. Should be set to 0

2023-02-28 14:49 UTC, sunnya97 commented
Gas estimation still not working properly (at least for BNB)

<img width="665" alt="CleanShot 2023-02-28 at 07 49 07@2x" src="https://user-images.githubusercontent.com/979241/221889129-f4
<img width="1213" alt="CleanShot 2023-02-28 at 07 49 02@2x" src="https://user-images.githubusercontent.com/979241/221889136-853687ba-0eda-4aaf-909d-5d46c5c6b5ab.png">
1dc2a9-e50b-4387-885d-fe7e13dfa3af.png">

2023-02-28 19:22 UTC, JoseRFelix approved these changes
LGTM! 🚀

2023-02-28 19:28 UTC, merged