feat: Create Wallet Registry
osmosis-labs/osmosis-frontend pull request #1477
Opened 2023-04-11 04:07 UTC by JoseRFelix

2023-04-27 15:33 UTC, jonator reviewed
When installing packages I'm getting many notifications that there are peer dependencies..

Is this something to be concerned with?

<img width="1525" alt="Screenshot 2023-04-26 at 7 32 23 PM" src="https://user-images.githubusercontent.com/4606373/234730414-13e65376-d566-4bd1-b326-e8dfd220f594.png">

2023-04-27 16:12 UTC, JoseRFelix commented on packages/web/hooks/wallet-select.tsx
This file is a replacement for `use-keplr`. It's a React context. It's a mix between hook and component. So it's not clear if we should add it to `components` or `hooks`. I think this would be a good opportunity to create a new `context` folder. wdyt?

2023-04-27 16:35 UTC, JoseRFelix commented on packages/stores/src/account/base.ts
> +    this.refresh();
This was my first idea when adding reactivity to the wallet manager. After looking at the source code, WalletManager is a subclass. According to Mobx docs, we can't use `makeAutoObservable` unless it's a parent class. I also tried using `makeObservable` but that is more error-prone and tedious than a `refresh` function. 

I think the `refresh` method is not too bad. We are using the same approach as [Cosmoskit to refresh the UI](https://github.com/cosmology-tech/cosmos-kit/blob/5b8558c804d625948e3963ae540506cfd48e0cb9/packages/react-lite/src/provider.tsx#L81-L101). It's an interesting agnostic solution they came out with. It's not as granular as Mobx, but it's good enough that it only re-renders when something relevant has changed.

2023-05-02 14:22 UTC, jonator approved these changes
Minor nits

2023-05-02 15:35 UTC, JoseRFelix commented on packages/stores/src/account/base.ts
> +          window?.localStorage.removeItem(CosmosKitAccountsLocalStorageKey);
I wish we could implement this! However, Cosmoskit manages local storage calls internally, so we cannot utilize our kv store.

2023-05-10 00:02 UTC, jonator requested changes
Related to https://github.com/osmosis-labs/osmosis-frontend/pull/1549#issuecomment-1541028851

Should prob double check turbo.json config to make sure it's config'd properly to catch any unique generated telescope output of the new `proto-codecs` package (the `build.outputs` field). That way, when cache's get replayed, we get the generated code as well.

It also doesn't seem like it's been integrated into the monorepo in the first place.

2023-05-19 02:38 UTC, JoseRFelix commented
> Related to [#1549 (comment)](https://github.com/osmosis-labs/osmosis-frontend/pull/1549#issuecomment-1541028851)
> 
> Should prob double check turbo.json config to make sure it's config'd properly to catch any unique generated telescope output of the new `proto-codecs` package (the `build.outputs` field). That way, when cache's get replayed, we get the generated code as well.
> 
> It also doesn't seem like it's been integrated into the monorepo in the first place.


This was resolved in #1549

2023-05-19 02:39 UTC, merged