wip: wallet select modal
osmosis-labs/osmosis-frontend pull request #1638
Opened 2023-06-06 03:09 UTC by JoseRFelix

…ct-modal-layout

## What is the purpose of the change

Adds a new onboarding modal for Wallet Select. 

### ClickUp Task

Please provide a link to the ClickUp task for this pull request:

[ClickUp Task URL](Wallet Select Modal UX Improvements)

## Key Workflows to test

\*(Enter here)

## Testing and Verifying

_(Please pick either of the following options)_

This change has been tested locally by rebuilding the website and verified content and links are expected

_(or)_

This change has not been tested locally, because (to-be-explained-why...)

## Documentation and Release Note

- Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
- How is the feature or change documented? (not applicable / [Osmosis web dev guide](https://docs.osmosis.zone/developing/web-dev-guide.html) / not documented)

2023-07-25 10:40 UTC, jonator commented on packages/web/modals/wallet-select.tsx
> +                  are ever with us.
Needs to be translated.

2023-07-25 10:40 UTC, jonator commented on packages/web/modals/wallet-select.tsx
> +          below to connect.
Also translated

2023-07-29 12:20 UTC, jonator requested changes

2023-07-29 12:20 UTC, jonator commented on packages/web/modals/wallet-select.tsx
> +  const wallets = [...WalletRegistry]
Should this be a useMemo? Or is this component not expected to render much?

2023-07-29 12:20 UTC, jonator commented on packages/web/modals/wallet-select.tsx
> +  const categories = wallets.reduce(
useMemo here as well

2023-07-29 12:20 UTC, jonator requested changes
Can we add arrow buttons here, like in instagram flow?

The dots are hard to use to navigate, but are nice to jump directly to slides.
<img width="510" alt="Screenshot 2023-07-29 at 7 09 23 AM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/4606373/ec3719e3-4e5b-4896-b8a1-bc656124ca48">

Nit, but since we're editing this area:

Can we match the wallet icon with the OSMO icon? Looks like it's osmoverse 300.
<img width="251" alt="Screenshot 2023-07-29 at 7 10 23 AM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/4606373/8b131384-e102-4590-a7b3-ff11a2295a5c">

Bug: when I disconnected Keplr then clicked Keplr Mobile (to see the QR code) I saw this error appear behind the modal:
<img width="982" alt="Screenshot 2023-07-29 at 7 18 56 AM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/4606373/19495ee4-adab-4d59-9e59-6086637cade5">

2023-07-29 16:52 UTC, JoseRFelix commented
@jonator Thanks for the feedback and review! I have addressed it accordingly. 

> Bug: when I disconnected Keplr then clicked Keplr Mobile (to see the QR code) I saw this error appear behind the modal:

This happens because the `NEXT_PUBLIC_WALLETCONNECT_PROJECT_KEY` is not set on the `.env` file

2023-07-31 12:28 UTC, jonator approved these changes

2023-07-31 12:28 UTC, jonator commented
Great work!

2023-07-31 15:52 UTC, merged