(CL) Make Increase Liquidity Modal Mobile Responsive
osmosis-labs/osmosis-frontend pull request #1651
Opened 2023-06-10 06:04 UTC by JoseRFelix

2023-06-10 10:35 UTC, jonator reviewed
Nits

2023-06-10 10:35 UTC, jonator commented on packages/web/modals/increase-concentrated-liquidity.tsx
> +      </div>
i think the basemodal provides a close button for use if we simply set hideclosebutton=false

2023-06-10 10:35 UTC, jonator commented on packages/web/components/cards/my-position/status.tsx
> +  className?: string;
giga nit: we have `CustomClasses` type that adds this

2023-06-10 10:37 UTC, jonator requested changes
See some issues with arrangement of +/- buttons on iPhone
<img width="379" alt="Screenshot 2023-06-10 at 12 28 50 PM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/4606373/b516cda1-04ce-41d5-903c-08cb431af6ce">

2023-06-10 17:50 UTC, JoseRFelix commented
> See some issues with arrangement of +/- buttons on iPhone

Interesting I'm getting the correct size on the first load. It could be an issue with `onresize` event. Can you confirm if it appears correctly when you load it for the first time on your side?

![image](https://github.com/osmosis-labs/osmosis-frontend/assets/21092519/127a9623-6c4d-424a-a8fe-572a20b599f3)

2023-06-13 11:19 UTC, jonator approved these changes

2023-06-14 07:42 UTC, merged