WIP: e2e swap quotes test in one for zero direction (right)
osmosis-labs/osmosis-frontend pull request #1773
Opened 2023-07-07 20:54 UTC by p0mvn

## What is the purpose of the change

E2E quotes test for swapping one for zero (right). Note that it requires a localosmosis change to increase the amounts of genesis tokens

Relevant osmosis PR: TBD

## Brief Changelog
- added more simple and edge case tests
- added a complex test of swapping to far away tick that is near max spot price along a range of initialized positons

## Documentation and Release Note

2023-07-07 20:58 UTC, p0mvn commented on packages/stores/src/account/osmosis/index.ts
> +        const token_min_amount1 = "0";
Temporary change. Had tests broken because of this. Need to figure out

2023-07-07 20:58 UTC, p0mvn commented on packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
> +    protected readonly maxNumRequeriesPerDenom = 100
temporary: need to experiment and tweak this more

2023-07-07 23:19 UTC, jonator commented
@p0mvn https://github.com/osmosis-labs/osmosis-frontend/pull/1775

This may fix things for you

2023-07-07 23:34 UTC, p0mvn commented on packages/pools/src/concentrated.ts
> +      effectivePriceOutOverIn: invertIfNonZero(effectivePriceInOverOut),
link

2023-07-08 22:03 UTC, jonator requested changes

2023-07-08 22:03 UTC, jonator commented on packages/stores/src/__tests_e2e__/stop-osmosisd.sh
Please revert

2023-07-08 22:03 UTC, jonator commented on packages/stores/src/__tests_e2e__/start-osmosisd.sh
Please revert

2023-07-08 22:03 UTC, jonator commented on packages/stores/src/__tests_e2e__/global-setup.ts
Please revert

2023-07-08 22:03 UTC, jonator commented on packages/stores/src/__tests_e2e__/test-env.ts
> +    rest: "http://207.154.252.194:1317",
Please revert

2023-07-08 22:03 UTC, jonator commented on packages/stores/src/account/__tests_e2e__/swap-exact-in-positions.spec.ts
> +        );
Please remove all logs

2023-07-08 22:03 UTC, jonator commented on packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
> +
Please clean this up

2023-07-09 03:19 UTC, p0mvn commented on packages/stores/src/queries/concentrated-liquidity/tick-data-provider.ts
> +    protected readonly nextTicksRampMultiplier = new Int(9),
Confirmed that this is the smallest possible to allow all tests to pass (and cover entire tick range)

2023-07-09 15:08 UTC, jonator requested changes
Please fix build errors

2023-07-10 14:00 UTC, merged

2023-07-11 01:17 UTC, p0mvn commented on packages/math/src/pool/concentrated/tick.ts
> +    }
here