Reposition and optimize token images
osmosis-labs/osmosis-frontend pull request #1937
Opened 2023-07-31 10:45 UTC by dogemos

## What is the purpose of the change

Token images are currently not standardized in positioning nor optimized. This PR repositions/edits token icons to follow icon keylines, and then was optimized by using ImgOptim at 80% quality.

### ClickUp Task

n/a

## Brief Changelog

- Reposition to standardize most token icons to fit within icon keylines
- Run ImageOptim at 80% to minimize file size

## Testing and Verifying

- Verified by checking preview link

## Documentation and Release Note

n/a

2023-07-31 12:19 UTC, jonator commented on packages/web/public/tokens/8ball.svg
Looks like this one lost some content

2023-07-31 12:21 UTC, jonator commented
Thanks for doing this!

2023-07-31 15:16 UTC, jonator commented
FYI next.js optimizes images for us at build time, but it doesn't do anything to SVGs. So trimming SVGs of detail should improve performance.

2023-07-31 19:35 UTC, JeremyParish69 commented
After reviewing, I'm seeing that this ruins most of the images. I recommend we do not proceed with this

regarding: -Reposition to standardize most token icons to fit within icon keylines
It looks like some non-circular token logos been shrunk to fit inside a circle and sometimes have had the extra background space filled in the same color as the original background was. This was not applied consistently at all.
-I'd like to ask: is this something we want to enforce? Many token logos either are an irregular shape, but all of it's opaque content fits within an inscribed circle. And then there are token logos that are irregularly shaped or are perfectly square that have opaque content beyond the inscribed circle; do we want those to be shrunk such that they would fit inside a circle? Do we want 0 transparency within the circle?

regarding: -Standardize all token sizes to 200x200px 
This was not applied consistently at all. However, if 200x200 is a good size, then I can start encouraging or personally re-create token logos to be exactly this size for the frontend going forward. 

It also inconsistently applies a padding on token logos which will shrink the token logos, so we'll have tokens appear to be different sizes because of the transparent padding on some of them. We should aim to have 0 additional padding.

2023-07-31 19:38 UTC, JeremyParish69 requested changes
This should not proceed. We should address this in stages. Logos that aren't circular should be handled individually. This should not be applied to SVGs. Resizing to 200x200 can be handled separately. Then a final optimization of PNGs shouldn't cause much trouble.

2023-08-21 20:43 UTC, jonator commented
Stale

2023-08-21 20:43 UTC, closed without merging