Add packages
osmosis-labs/osmosis-frontend pull request #2152
Opened 2023-09-15 17:01 UTC by MaxMillington

Adding Utils/Types packages

2023-09-16 15:13 UTC, ValarDragon approved these changes
ty!

2023-09-16 21:10 UTC, jonator approved these changes

2023-09-18 17:48 UTC, JoseRFelix requested changes

2023-09-18 17:48 UTC, JoseRFelix commented on packages/types/package.json
> +  "name": "types",
We should adhere to our package naming convention within the repository

```suggestion
  "name": "@osmosis-labs/types",
```

2023-09-18 17:48 UTC, JoseRFelix commented on packages/utils/package.json
> +  "name": "utils",
Same as above 
```suggestion
  "name": "@osmosis-labs/utils",
```

2023-09-19 15:34 UTC, JoseRFelix approved these changes

2023-09-19 17:58 UTC, merged