Add fuzzy filter hook
osmosis-labs/osmosis-frontend pull request #233
Opened 2022-02-04 18:09 UTC by jonator

Closes #232 .

I decided to use https://fusejs.io/ ([yarnpkg](https://yarnpkg.com/package/fuse.js)) to perform the searching. It's small at ~350kb yet will add a very rich fuzzy search experience. If we decide later, it would let us easily highlight/underline search results (I'm thinking we could highlight the various pool attributes right in the card as they search).

I also considered persisting the user's query across browser reloads via `localstorage`, but decided that that could be handled outside of this hook should we decide to do that later.

2022-02-06 22:56 UTC, jonator commented
Also plan on closing #237

2022-02-07 19:09 UTC, jonator commented
@Thunnini @delivan Let me know if you think the complexity around the table props is out of hand. My goal was to provide flexibility and good dev UX for table functionality but that comes with a lot of objects and their types flying around. Alternative ideas are welcome. One idea I have is to remove the table component entirely and have the table creators lay out the child elements every time. As that's basically what they're doing with columnDefs and rowDefs as needed.

2022-02-10 13:01 UTC, delivan requested changes

2022-02-10 13:01 UTC, delivan commented on packages/web/components/control/page-list.tsx
>    const [textEditing, setIsEditing] = useState(false);
I think it would be clearer to add `set` as prefix to state variable name itself.  Also, I recommend to name variable `Is~~` for boolean.

2022-02-10 15:48 UTC, jonator commented on packages/web/pages/assets/index.tsx
> +  const [sortDirection, setSortDirection] = useState<SortDirection | undefined>(
Good idea!

2022-02-10 16:20 UTC, merged