feat: Display Unlisted Assets Based on Query Key
osmosis-labs/osmosis-frontend pull request #2442
Opened 2023-11-15 20:31 UTC by JoseRFelix

## What is the purpose of the change

To view unlisted assets for testing, append the following query parameter to the Osmosis URL:

```
?show_unlisted_assets=true
```

They'll be enabled for the tab's session. If you'd like to disable it, either open a new tab without the query parameter or restart the browser.

## Testing and Verifying

- [ ] Unlisted assets are enabled for a session when `?show_unlisted_assets` is appended to the URL
- [ ] Unlisted assets should not be visible by default

2023-11-15 20:47 UTC, jonator approved these changes

2023-11-15 22:26 UTC, JeremyParish69 requested changes
As of the lasted successful build, I am still able to see tokens that should be unlisted (sqOSMO and sqATOM). Upon appending ?show_unlisted_assets to the assets page, I still cannot see QWOYN, which has been added to assetlist.

Also, when appending ?show_unlisted_assets to the URL, as soon as I click to a different page in the nav bar, the ?show_unlisted_assets is removed from the URL. It will be confusing for validators to have to manually add that every time they switch to a new page. Having ?show_unlisted_assets persist is desired.

2023-11-15 22:29 UTC, JoseRFelix commented
> As of the lasted successful build, I am still able to see tokens that should be unlisted (sqOSMO and sqATOM). Upon appending ?show_unlisted_assets to the assets page, I still cannot see QWOYN, which has been added to assetlist.
> 
> Also, when appending ?show_unlisted_assets to the URL, as soon as I click to a different page in the nav bar, the ?show_unlisted_assets is removed from the URL. It will be confusing for validators to have to manually add that every time they switch to a new page. Having ?show_unlisted_assets persist is desired.

My bad I forgot to add the =true to the instructions. Please try with this param `?show_unlisted_assets=true`. It should look like this https://osmosis-frontend-git-jose-use-feature-flag-to-ffce6e-osmo-labs.vercel.app/?show_unlisted_assets=true. 

Btw, it's fine if it goes away. Unlisted assets will be visible for that session

2023-11-16 17:50 UTC, JeremyParish69 approved these changes
works well!

2023-11-16 17:50 UTC, merged