add onramp.money
osmosis-labs/osmosis-frontend pull request #2538
Opened 2023-12-12 04:54 UTC by sajwanAshish

## What is the purpose of the change

adds another option to buy tokens from (onramp.money)

### ClickUp Task

[ClickUp Task URL](PASTE_CLICKUP_TASK_URL_HERE)

## Brief Changelog
- when click on buy button, it add 1 more option called onramp.money.
- opens onramp.money on a iframe.
- users sees how much they are going to pay & how much coins are they coin to get.
- user address is prefilled
- user needs to pay & received token in their wallet

## Testing and Verifying

## Documentation and Release Note

2023-12-12 18:11 UTC, jonator commented on packages/web/localizations/en.json
Reminder to run `yarn machine-translate` at the root to get other languages

2023-12-12 18:26 UTC, MaxMillington commented
Looks like we might have some build failures due to type errors. Can you run `yarn build` locally and get it to pass? 

<img width="1523" alt="Screenshot 2023-12-12 at 11 26 38 AM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/11064595/0216acf6-c6ea-4492-9ca5-858a27ac1797">

2023-12-13 06:50 UTC, sajwanAshish commented on packages/web/localizations/en.json
done

2023-12-13 11:17 UTC, sajwanAshish commented
> Looks like we might have some build failures due to type errors. Can you run `yarn build` locally and get it to pass?
> 
> <img alt="Screenshot 2023-12-12 at 11 26 38 AM" width="1523" src="https://private-user-images.githubusercontent.com/11064595/289966236-0216acf6-c6ea-4492-9ca5-858a27ac1797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjYyMjAsIm5iZiI6MTcwMjQ2NTkyMCwicGF0aCI6Ii8xMTA2NDU5NS8yODk5NjYyMzYtMDIxNmFjZjYtYzZlYS00NDkyLTljYTUtODU4YTI3YWMxNzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTUzMGYwYmIwODI3N2QwMmRmZDJmYmM1OGI5OWM5MWRkNDdkOGIzNzdjZjUzZjM5NzVlNzRiMDYzNDhhMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6jA0kCkVDngJgf8ruxJxRSti5o0P8EnGloI9Br_AIY">

m using `yarn run generate` command to generate the `sprite-ids.ts` but its not working..

looks like sprite-ids.ts is build using `public/icons/sprite.svg` file - mentioned in `generate-sprite-ids.ts` file

how to i update `public/icons/sprite.svg` file ?

2023-12-13 15:13 UTC, MaxMillington commented
> > Looks like we might have some build failures due to type errors. Can you run `yarn build` locally and get it to pass?
> > <img alt="Screenshot 2023-12-12 at 11 26 38 AM" width="1523" src="https://private-user-images.githubusercontent.com/11064595/289966236-0216acf6-c6ea-4492-9ca5-858a27ac1797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjYyMjAsIm5iZiI6MTcwMjQ2NTkyMCwicGF0aCI6Ii8xMTA2NDU5NS8yODk5NjYyMzYtMDIxNmFjZjYtYzZlYS00NDkyLTljYTUtODU4YTI3YWMxNzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTUzMGYwYmIwODI3N2QwMmRmZDJmYmM1OGI5OWM5MWRkNDdkOGIzNzdjZjUzZjM5NzVlNzRiMDYzNDhhMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6jA0kCkVDngJgf8ruxJxRSti5o0P8EnGloI9Br_AIY">
> 
> m using `yarn run generate` command to generate the `sprite-ids.ts` but its not working..
> 
> looks like sprite-ids.ts is build using `public/icons/sprite.svg` file - mentioned in `generate-sprite-ids.ts` file
> 
> how to i update `public/icons/sprite.svg` file ?

Sent you a slack

2023-12-13 15:53 UTC, sajwanAshish commented
> > > Looks like we might have some build failures due to type errors. Can you run `yarn build` locally and get it to pass?
> > > <img alt="Screenshot 2023-12-12 at 11 26 38 AM" width="1523" src="https://private-user-images.githubusercontent.com/11064595/289966236-0216acf6-c6ea-4492-9ca5-858a27ac1797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjYyMjAsIm5iZiI6MTcwMjQ2NTkyMCwicGF0aCI6Ii8xMTA2NDU5NS8yODk5NjYyMzYtMDIxNmFjZjYtYzZlYS00NDkyLTljYTUtODU4YTI3YWMxNzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTUzMGYwYmIwODI3N2QwMmRmZDJmYmM1OGI5OWM5MWRkNDdkOGIzNzdjZjUzZjM5NzVlNzRiMDYzNDhhMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6jA0kCkVDngJgf8ruxJxRSti5o0P8EnGloI9Br_AIY">
> > 
> > 
> > m using `yarn run generate` command to generate the `sprite-ids.ts` but its not working..
> > looks like sprite-ids.ts is build using `public/icons/sprite.svg` file - mentioned in `generate-sprite-ids.ts` file
> > how to i update `public/icons/sprite.svg` file ?
> 
> Sent you a slack

fixed build issues

2023-12-13 16:37 UTC, CryptoAssassin1 commented
in logo ON text is only visible when you hover the mouse.
![Screenshot from 2023-12-13 21-34-58](https://github.com/osmosis-labs/osmosis-frontend/assets/103904125/67ffb75c-5017-4f42-bde6-b6b71ba311dd)
![Screenshot from 2023-12-13 21-34-49](https://github.com/osmosis-labs/osmosis-frontend/assets/103904125/0e6dbe2f-ce40-44f2-8a60-f31a720b5140)

2023-12-13 16:42 UTC, kamal-sutra commented
Says both Osmo and USDC supported but only Osmo is available currently. Shouldn't be a blocker if USDC is coming soon.

<img width="250" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/7236d864-e488-46a2-be79-95d8c26c4211">
<img width="269" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/8f6cd74c-8fc9-4a27-8ac0-db69221fcebd">

2023-12-13 16:50 UTC, kamal-sutra commented
Couldn't link TG bot for a Portugal phone number.
Din't get OTP for an Indian phone number

![image](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/eba164bc-31a1-45fa-b092-33ed6d3289e5)
![image](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/47a70db3-d047-4890-9f09-5e046c9f2180)

2023-12-13 16:55 UTC, sajwanAshish commented
> in logo ON text is only visible when you hover the mouse. ![Screenshot from 2023-12-13 21-34-58](https://private-user-images.githubusercontent.com/103904125/290262083-67ffb75c-5017-4f42-bde6-b6b71ba311dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODY3MTksIm5iZiI6MTcwMjQ4NjQxOSwicGF0aCI6Ii8xMDM5MDQxMjUvMjkwMjYyMDgzLTY3ZmZiNzVjLTUwMTctNGY0Mi1iZGU2LWI2YjcxYmEzMTFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWVmOGU3NGU4MGUwY2YzMjlkMjFmNTI5OWIxMGQzZjFhNWE5Y2EwODE4NzE2NDJlOGIyZTY5NjRhMWVmOTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-2TzecZxA3ti-lAYac9XC-CXAVHskx3KsHU4ZHBGzMg) ![Screenshot from 2023-12-13 21-34-49](https://private-user-images.githubusercontent.com/103904125/290262123-0e6dbe2f-ce40-44f2-8a60-f31a720b5140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODY3MTksIm5iZiI6MTcwMjQ4NjQxOSwicGF0aCI6Ii8xMDM5MDQxMjUvMjkwMjYyMTIzLTBlNmRiZTJmLWNlNDAtNDRmMi04YTYwLWYzMWE3MjBiNTE0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWI1MjBkNDQ2MjRhNjE3M2RjYTQ3OGRjYTAyYTA5Nzg0NTMwMzJmNmQyYmJlMjI1NjQxYjJjMjViNThjMTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ruuvSQS4RagMcqHCYD8sQFJB-yEmowJvK0eL0nysP3Q)

logo updated

2023-12-13 16:56 UTC, arispech commented
Osmo logo does not look good, it looks pixelated and unaligned.
<img width="397" alt="Screenshot 2023-12-13 at 11 52 18 AM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/56182049/7330c2c6-7aaf-4417-b4f4-052771c0b4b4">

2023-12-13 16:59 UTC, sajwanAshish commented
> Couldn't link TG bot for a Portugal phone number. Din't get OTP for an Indian phone number
> 
> ![image](https://private-user-images.githubusercontent.com/116148606/290265979-eba164bc-31a1-45fa-b092-33ed6d3289e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODY3MTksIm5iZiI6MTcwMjQ4NjQxOSwicGF0aCI6Ii8xMTYxNDg2MDYvMjkwMjY1OTc5LWViYTE2NGJjLTMxYTEtNDVmYS1iMDkyLTMzZWQ2ZDMyODllNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWZlMTE2MTE2MTFhNmI2MTMxYmJmYjMxODExYzJkOTU3M2U4YzVmOWY3MTdmMGU5MmQwZDE3YzQ0NTkxZTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.czJlAXAAEH7RQcJcWMzMXm9r5CF9LifrbrVk1C_IYiM) ![image](https://private-user-images.githubusercontent.com/116148606/290266361-47a70db3-d047-4890-9f09-5e046c9f2180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODY3MTksIm5iZiI6MTcwMjQ4NjQxOSwicGF0aCI6Ii8xMTYxNDg2MDYvMjkwMjY2MzYxLTQ3YTcwZGIzLWQwNDctNDg5MC05ZjA5LTVlMDQ2YzlmMjE4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmU4MmQzZmZiMjRkMDliNmY0M2VhMmY4YmY5YTg0MTQ0ODQzYTgwZDRhNDBjOTk2YmMzOGQ5OWU4OWY5NWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PaOInj2uIqtCeNFAcTc6qSm2aMDkRAFdQAxHrMQgkWk)

Here is a dummy phone number you can use

Phone Number: +91 1122334455

OTP :  123456

2023-12-13 17:01 UTC, CryptoAssassin1 commented
There should be limit for integers so things dont overlap.
![Screenshot from 2023-12-13 21-59-33](https://github.com/osmosis-labs/osmosis-frontend/assets/103904125/4a4c8526-148c-47f4-b0b6-989e5c487aab)

2023-12-14 16:54 UTC, kamal-sutra commented
@sajwanAshish I tried with dummy number and scanned QR to pay with googlepay/phonepe with 200Rs.  dint went through. Is it because of dummy number or payments aren't open yet? 
We would like to test full version end to end with real phone numbers (EU, US, IND etc) and Tg accounts to make sure full integrations works well.

2023-12-18 05:13 UTC, sajwanAshish commented
> There should be limit for integers so things dont overlap. ![Screenshot from 2023-12-13 21-59-33](https://private-user-images.githubusercontent.com/103904125/290269368-4a4c8526-148c-47f4-b0b6-989e5c487aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzY2NDQsIm5iZiI6MTcwMjg3NjM0NCwicGF0aCI6Ii8xMDM5MDQxMjUvMjkwMjY5MzY4LTRhNGM4NTI2LTE0OGMtNDdmNC1iMGI2LTk4OWU1YzQ4N2FhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNTEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjlmNDYxMjIzOWQyYzliYWQ3OTFiZTA4YzEzMGQ5Y2IxYzhjMjNhMjYyOTk4OTUzMmRmNWYwNjQ3NjVlYjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._-bavC4VcMFf0oNN8RjMKyg9Z3B632g9L2nAf3obXcM)

this is sorted

2023-12-18 05:14 UTC, sajwanAshish commented
> in logo ON text is only visible when you hover the mouse. ![Screenshot from 2023-12-13 21-34-58](https://private-user-images.githubusercontent.com/103904125/290262083-67ffb75c-5017-4f42-bde6-b6b71ba311dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzY2NDQsIm5iZiI6MTcwMjg3NjM0NCwicGF0aCI6Ii8xMDM5MDQxMjUvMjkwMjYyMDgzLTY3ZmZiNzVjLTUwMTctNGY0Mi1iZGU2LWI2YjcxYmEzMTFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNTEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGJjYWI1MzI2NDM0NzEwNjZiOWFiZDQxM2YwZDFlYWRjN2Y0OTQxYjFkYjhlMzg0M2QxNTk3YzBhNGIwYTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WUdsYVpHaD34vypPhNArypFPCe0-Y0KkdeAxNH_8joI) ![Screenshot from 2023-12-13 21-34-49](https://private-user-images.githubusercontent.com/103904125/290262123-0e6dbe2f-ce40-44f2-8a60-f31a720b5140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzY2NDQsIm5iZiI6MTcwMjg3NjM0NCwicGF0aCI6Ii8xMDM5MDQxMjUvMjkwMjYyMTIzLTBlNmRiZTJmLWNlNDAtNDRmMi04YTYwLWYzMWE3MjBiNTE0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNTEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzRkMTQzMTZlN2JhMGEyOGM3YTEzN2U4ZDBiYTNjOWI1ZTdmMzk0YTg0NTQ0Y2VlNGFiZTg0ZmUxYzNmYmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m3YTdiM1wIi6V7b3efhW8kKC9fFWycVZzZ_kGVcU95c)

sorted

2023-12-18 07:47 UTC, DavideSegullo approved these changes

2023-12-18 09:35 UTC, sajwanAshish commented
i see there are conflicts in localizations files... shall i go ahead & fix conflicts or your team will take care of it

2023-12-18 09:46 UTC, DavideSegullo commented
> i see there are conflicts in localizations files... shall i go ahead & fix conflicts or your team will take care of it
> 
> @DavideSegullo @kamal-sutra

You can fix them

2023-12-19 05:11 UTC, sajwanAshish commented
> Osmo logo does not look good, it looks pixelated and unaligned. <img alt="Screenshot 2023-12-13 at 11 52 18 AM" width="397" src="https://private-user-images.githubusercontent.com/56182049/290267639-7330c2c6-7aaf-4417-b4f4-052771c0b4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjI5ODksIm5iZiI6MTcwMjk2MjY4OSwicGF0aCI6Ii81NjE4MjA0OS8yOTAyNjc2MzktNzMzMGMyYzYtN2FhZi00NDE3LWI0ZjQtMDUyNzcxYzBiNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA1MTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NTIyZjExMDNmZDI3ZDhmZjU2ZDM0MDJlYjEzZjcyYzQ1YmZlMmQ4MmRhOTY3Y2JhMGNjZjY5OTU3NTlhZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g6Xu6rCw-VgQdWG9xK9PZOA2Ve7yQuTVozAI6640FF0">

fixed

2023-12-19 17:28 UTC, MaxMillington commented
@sajwanAshish looks like you just need to rebase against stage to resolve conflicts

2023-12-21 11:24 UTC, kamal-sutra commented
Tried with Indian mobile number- KYC done in 5min.
Purchase with QR done in 5min
Sending osmo to my addy +5min
In 15min all done end to end.

2023-12-21 11:33 UTC, CryptoAssassin1 approved these changes

2023-12-21 12:27 UTC, kamal-sutra commented
@sajwanAshish only inr fiat available for now? eur or usd?

2023-12-21 18:18 UTC, jonator requested changes
I got the following error when opening the modal from sidebar:

<img width="421" alt="Screenshot 2023-12-21 at 12 17 56 PM" src="https://github.com/osmosis-labs/osmosis-frontend/assets/4606373/837579b1-76ec-44f6-bb94-0bbb65446447">

Also, I will say it was quite slow for me.

2024-01-02 21:10 UTC, MaxMillington commented
@sajwanAshish any update on this?

2024-01-03 07:35 UTC, sajwanAshish commented
> 123456

This test number has changed,

this is for Germany (EU) 
+49 1122334455 | 123456

for india plz use real numbers..
-- | --

2024-01-03 18:36 UTC, kamal-sutra commented
@sajwanAshish it is not giving EUR option
<img width="252" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/b5bcbba5-77ba-4afa-8545-bc85fa7be99e">

2024-01-09 17:47 UTC, kamal-sutra commented
> 1122334455

EUR option shows now, just couldn't test with dummy number, as it sends otp to that number

2024-01-09 17:50 UTC, sajwanAshish commented
Pls try entering 123456 as otp

On Tue, 9 Jan 2024, 11:17 pm kamal-sutra, ***@***.***> wrote:

> 1122334455
>
> EUR option shows now, just couldn't test with dummy number, as it sends
> otp to that number
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/osmosis-labs/osmosis-frontend/pull/2538#issuecomment-1883515287>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APTIZJ4WAUZDMXMEBGNA5ADYNV7EVAVCNFSM6AAAAABAQ25SA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBTGUYTKMRYG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-10 14:51 UTC, kamal-sutra commented
> > 1122334455

<img width="223" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/490ed842-ce65-4b8f-ba3f-51d7a0e3c365">

2024-01-10 15:00 UTC, sajwanAshish commented
> > > 1122334455
> 
> <img alt="image" width="223" src="https://private-user-images.githubusercontent.com/116148606/295605758-490ed842-ce65-4b8f-ba3f-51d7a0e3c365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTg5ODUsIm5iZiI6MTcwNDg5ODY4NSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjA1NzU4LTQ5MGVkODQyLWNlNjUtNGI4Zi1iYTNmLTUxZDdhMGUzYzM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNDU4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGY5ZDVjOTk2MTg3NDM2ODE1OWZmMTdjZjY5NWEzZDEyYTVjNWViNzMxMjgzMjk5MTRlYmMyZjAwZDA4ZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IATZr70tgSK6ohFPTAWkHoGg-JNcbqVCYqOLjtmEBGU">

plz try now

2024-01-10 15:12 UTC, kamal-sutra commented
> > > > 1122334455
> > 
> > 
> > <img alt="image" width="223" src="https://private-user-images.githubusercontent.com/116148606/295605758-490ed842-ce65-4b8f-ba3f-51d7a0e3c365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTg5ODUsIm5iZiI6MTcwNDg5ODY4NSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjA1NzU4LTQ5MGVkODQyLWNlNjUtNGI4Zi1iYTNmLTUxZDdhMGUzYzM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNDU4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGY5ZDVjOTk2MTg3NDM2ODE1OWZmMTdjZjY5NWEzZDEyYTVjNWViNzMxMjgzMjk5MTRlYmMyZjAwZDA4ZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IATZr70tgSK6ohFPTAWkHoGg-JNcbqVCYqOLjtmEBGU">
> 
> plz try now

got Fetching bank details for 5min and then this
<img width="227" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/7b7729e6-ac41-4b19-a66e-f8de87b6a108">

2024-01-10 16:36 UTC, sajwanAshish commented
> > > > > 1122334455
> > > 
> > > 
> > > <img alt="image" width="223" src="https://private-user-images.githubusercontent.com/116148606/295605758-490ed842-ce65-4b8f-ba3f-51d7a0e3c365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTg5ODUsIm5iZiI6MTcwNDg5ODY4NSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjA1NzU4LTQ5MGVkODQyLWNlNjUtNGI4Zi1iYTNmLTUxZDdhMGUzYzM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNDU4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGY5ZDVjOTk2MTg3NDM2ODE1OWZmMTdjZjY5NWEzZDEyYTVjNWViNzMxMjgzMjk5MTRlYmMyZjAwZDA4ZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IATZr70tgSK6ohFPTAWkHoGg-JNcbqVCYqOLjtmEBGU">
> > 
> > 
> > plz try now
> 
> got Fetching bank details for 5min and then this <img alt="image" width="227" src="https://private-user-images.githubusercontent.com/116148606/295612251-7b7729e6-ac41-4b19-a66e-f8de87b6a108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDE5NjEsIm5iZiI6MTcwNDkwMTY2MSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjEyMjUxLTdiNzcyOWU2LWFjNDEtNGIxOS1hNjZlLWY4ZGU4N2I2YTEwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNTQ3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDYwYmRiMDhjZmU4NTBiODI4NzIxNDUxMTY4MmZkM2QyNDBhYmEzMTU1OWRlMGQ5ZjZmMDE0ZmVkNzQxZGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._skpiCEhArIETuFo8WFP98SLjw3Ed3Vsakbh2XFDbpI">

Please try it again..

2024-01-10 16:52 UTC, kamal-sutra commented
> > > > > > 1122334455
> > > > 
> > > > 
> > > > <img alt="image" width="223" src="https://private-user-images.githubusercontent.com/116148606/295605758-490ed842-ce65-4b8f-ba3f-51d7a0e3c365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTg5ODUsIm5iZiI6MTcwNDg5ODY4NSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjA1NzU4LTQ5MGVkODQyLWNlNjUtNGI4Zi1iYTNmLTUxZDdhMGUzYzM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNDU4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGY5ZDVjOTk2MTg3NDM2ODE1OWZmMTdjZjY5NWEzZDEyYTVjNWViNzMxMjgzMjk5MTRlYmMyZjAwZDA4ZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IATZr70tgSK6ohFPTAWkHoGg-JNcbqVCYqOLjtmEBGU">
> > > 
> > > 
> > > plz try now
> > 
> > 
> > got Fetching bank details for 5min and then this <img alt="image" width="227" src="https://private-user-images.githubusercontent.com/116148606/295612251-7b7729e6-ac41-4b19-a66e-f8de87b6a108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDE5NjEsIm5iZiI6MTcwNDkwMTY2MSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjEyMjUxLTdiNzcyOWU2LWFjNDEtNGIxOS1hNjZlLWY4ZGU4N2I2YTEwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNTQ3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDYwYmRiMDhjZmU4NTBiODI4NzIxNDUxMTY4MmZkM2QyNDBhYmEzMTU1OWRlMGQ5ZjZmMDE0ZmVkNzQxZGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._skpiCEhArIETuFo8WFP98SLjw3Ed3Vsakbh2XFDbpI">
> 
> Please try it again..

@sajwanAshish it is now giving me bank details. But i gave a dummy name as Recipient and i don't get the option to change to real name even after clearing cache. For now i will try with another wallet address

2024-01-10 16:56 UTC, kamal-sutra commented
@sajwanAshish Even from another wallet it is not giving me option to write new Recipient name. I guess it is already linked to the dummy german number. Can u provide option to edit Recipient name please. Else bank transfer might get declined/lost.
<img width="224" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/759ebabb-f32d-4190-a45d-d4c3da00d5d2">

2024-01-10 17:06 UTC, sajwanAshish commented
> @sajwanAshish Even from another wallet it is not giving me option to write new Recipient name. I guess it is already linked to the dummy german number. Can u provide option to edit Recipient name please. Else bank transfer might get declined/lost. <img alt="image" width="224" src="https://private-user-images.githubusercontent.com/116148606/295643504-759ebabb-f32d-4190-a45d-d4c3da00d5d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDY1MzksIm5iZiI6MTcwNDkwNjIzOSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjQzNTA0LTc1OWViYWJiLWYzMmQtNDE5MC1hNDVkLWQ0YzNkYTAwZDVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNzAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmQ3NjczZjg3MTlmMDM3Yjc3N2JkMjIyMDYzMDdiMzhmZGNlYTdlZjk0ZjIxNjVjYjRhNWY2NGNhNDFmNzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pFN55p6Q9J9RY9x6-szZWTW-3NC5A40Cs1KFmKeYRGU">

can we get on a call & sort out this out 

as you guys might want to test it for multiple countries before approving this change

2024-01-10 17:22 UTC, kamal-sutra commented
> > @sajwanAshish Even from another wallet it is not giving me option to write new Recipient name. I guess it is already linked to the dummy german number. Can u provide option to edit Recipient name please. Else bank transfer might get declined/lost. <img alt="image" width="224" src="https://private-user-images.githubusercontent.com/116148606/295643504-759ebabb-f32d-4190-a45d-d4c3da00d5d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDY1MzksIm5iZiI6MTcwNDkwNjIzOSwicGF0aCI6Ii8xMTYxNDg2MDYvMjk1NjQzNTA0LTc1OWViYWJiLWYzMmQtNDE5MC1hNDVkLWQ0YzNkYTAwZDVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNzAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmQ3NjczZjg3MTlmMDM3Yjc3N2JkMjIyMDYzMDdiMzhmZGNlYTdlZjk0ZjIxNjVjYjRhNWY2NGNhNDFmNzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pFN55p6Q9J9RY9x6-szZWTW-3NC5A40Cs1KFmKeYRGU">
> 
> can we get on a call & sort out this out
> 
> as you guys might want to test it for multiple countries before approving this change

Sure. can u send invite link to maquina.osmosis@gmail.com (but for tomorrow if possible, it's late night for me now)
cc @MaxMillington @CryptoAssassin1  if you wanna get on call

2024-01-11 13:29 UTC, kamal-sutra commented
Purchase with EUR is successful. 
Suggestions- 
Allow 'space' in Recipient name field;
A check box would be helpful for the user to make sure the Name, Phone number etc are provided correctly.

Good to merge

2024-01-11 13:30 UTC, kamal-sutra approved these changes

2024-01-11 18:12 UTC, jonator approved these changes

2024-01-11 18:24 UTC, CryptoAssassin1 approved these changes

2024-01-11 18:34 UTC, merged

2024-01-12 07:12 UTC, kamal-sutra commented
@sajwanAshish IMP
i just tried another transfer. i think there is a payment method network issue. 
This din't happened during QA few days ago. Alternative option to transfer by bank is also not available. Bank depsoit details are not given.
![image](https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/f51fff49-a873-4b55-8cc0-871065cdd07c)

2024-01-12 07:26 UTC, sajwanAshish commented
> @sajwanAshish IMP i just tried another transfer. i think there is a payment method network issue. This din't happened during QA few days ago. Alternative option to transfer by bank is also not available. Bank depsoit details are not given. ![image](https://private-user-images.githubusercontent.com/116148606/296156990-f51fff49-a873-4b55-8cc0-871065cdd07c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDQ2NzMsIm5iZiI6MTcwNTA0NDM3MywicGF0aCI6Ii8xMTYxNDg2MDYvMjk2MTU2OTkwLWY1MWZmZjQ5LWE4NzMtNGI1NS04Y2MwLTg3MTA2NWNkZDA3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzI2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDRjMzM2YzY3YzlmNzlhMTJhMWFmYzFjOGJhZWU4MGQ0N2MyYTBhNmQyM2YwN2Q3OGY1MjRjYWMyNTg3YjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5HddMuK_Z74ZY_tzA2AsvUOmPeSLFFxh7Atup21a_0A)

should be working now..

2024-01-12 09:06 UTC, kamal-sutra commented
> > @sajwanAshish IMP i just tried another transfer. i think there is a payment method network issue. This din't happened during QA few days ago. Alternative option to transfer by bank is also not available. Bank depsoit details are not given. ![image](https://private-user-images.githubusercontent.com/116148606/296156990-f51fff49-a873-4b55-8cc0-871065cdd07c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDQ2NzMsIm5iZiI6MTcwNTA0NDM3MywicGF0aCI6Ii8xMTYxNDg2MDYvMjk2MTU2OTkwLWY1MWZmZjQ5LWE4NzMtNGI1NS04Y2MwLTg3MTA2NWNkZDA3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzI2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDRjMzM2YzY3YzlmNzlhMTJhMWFmYzFjOGJhZWU4MGQ0N2MyYTBhNmQyM2YwN2Q3OGY1MjRjYWMyNTg3YjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5HddMuK_Z74ZY_tzA2AsvUOmPeSLFFxh7Atup21a_0A)
> 
> should be working now..

Taking long time. Please check status
<img width="226" alt="image" src="https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/a58d350b-c4f0-4674-9de8-f3475024adca">