fix/ #2565 If I've already closed the banner, never have it show on on FE reload
osmosis-labs/osmosis-frontend pull request #2569
Opened 2023-12-16 13:57 UTC by HarjobandeepSingh

**What is the purpose of the change**
This pull request modifies the behavior of the announcement banner on the website. The change ensures that once a user closes the banner, it does not reappear upon page reload, improving the user experience.

**Brief Changelog**
Modified the AdBannerContent component to use local storage for tracking the visibility state of the banner.
Added a click event handler to the entire banner that sets the banner's visibility state in local storage and hides the banner.
Testing and Verifying
This change has been tested locally by rebuilding the website and verifying that the banner does not reappear after being closed and the page is reloaded.

**Documentation and Release Note**
This pull request introduces a change in user-facing behavior. Previously, the announcement banner would reappear every time the page was reloaded, even if the user had closed it. With this change, once the user closes the banner, it will not reappear upon page reload.

2023-12-16 13:58 UTC, HarjobandeepSingh commented
fix/ 2565

2023-12-16 14:06 UTC, HarjobandeepSingh commented
@MaxMillington Fix/

2023-12-18 16:42 UTC, jonator commented on packages/web/components/ad-banner/ad-banner-content.tsx
> +    }, []);
FYI we have a `useLocalstorageState` hook that may reduce some of this

2023-12-18 16:42 UTC, jonator commented on packages/web/components/ad-banner/ad-banner-content.tsx
> +);
Let's make sure we run lint fix

2023-12-18 18:32 UTC, MaxMillington commented
@HarjobandeepSingh please address @jonator's comments, then we will send to QA to review

2023-12-19 17:27 UTC, MaxMillington commented on packages/web/components/ad-banner/ad-banner-content.tsx
> -          // we pass this color in directly to avoid having to manually update our tailwind safelist with arbitrary values
would you add this comment back in please?

2023-12-19 17:41 UTC, arispech requested changes
The  banner still shows up for a second when you are refreshing the page


https://github.com/osmosis-labs/osmosis-frontend/assets/56182049/79872457-b89a-400b-ba6b-efb2916ffdc6

2023-12-19 17:46 UTC, CryptoAssassin1 commented
Same as Aris reported the banner appear disappear in a sec.

2023-12-19 18:22 UTC, kamal-sutra commented
@HarjobandeepSingh Also notice how the Swap window flashes/shakes when clicked on Swap button. 
https://github.com/osmosis-labs/osmosis-frontend/assets/116148606/89c9210c-3762-456a-8378-777be737b8f0

2023-12-21 10:24 UTC, CryptoAssassin1 commented
@HarjobandeepSingh banner is not loading now so cant test if its fixed or not.
file:///home/assassin/Downloads/Trade%20on%20Osmosis%20Zone%20(37).mp4

2023-12-21 12:42 UTC, HarjobandeepSingh commented
> @HarjobandeepSingh banner is not loading after deleting cookies and site data so cant test if its fixed or not.
> 
>  Trade.on.Osmosis.Zone.37.mp4

ok i will fix this

2023-12-21 12:50 UTC, HarjobandeepSingh commented
> banner is not loading after deleting cookies and site data so cant test if its fixed or not.

so i have to fix it or not ?

2023-12-21 19:16 UTC, MaxMillington requested changes
the banner doesn't show at all with the current code

2023-12-21 19:16 UTC, MaxMillington commented on packages/web/components/navbar/index.tsx
> +      null
this is just not going to show the banner ever right?

You can add a banner to test this by adding the following code to line 39 in feature-flag.ts

```
  : {
    localStorageKey: "test-key",
    enTextOrLocalizationPath: "test description",
  };
  ```

2024-01-08 21:55 UTC, MaxMillington commented
Thank you for your contribution. This issue has been completed [here](https://github.com/osmosis-labs/osmosis-frontend/pull/2654)

2024-01-08 21:55 UTC, closed without merging