Remove unlisted keyword filter of asset list
osmosis-labs/osmosis-frontend pull request #2659
Opened 2024-01-09 18:50 UTC by jonator

When creating asset tRPC procedure, I was under the impression that the "osmosis-unlisted" keyword meant that it should be filtered. This caused confusion when unlisted assets were not appearing in the frontend.

I removed the filter, and will consider adding a flag later that can be used to treat that keyword as a filter of the assets page.

2024-01-09 19:34 UTC, JoseRFelix commented
@jonator It looks like tests are failing

2024-01-09 21:15 UTC, JeremyParish69 requested changes
The Pool Detail swap modal now shows the unlisted token, but there are still console errors and there is no quoted price after inputting a swap in amount.

2024-01-10 19:20 UTC, JeremyParish69 requested changes
The Pool Detail swap modal now shows the unlisted token, but there are still console errors and there is no quoted price after inputting a swap in amount.
In addition, the frontend ignores the unlisted flag, which is a step backwards. We still need to hide tokens that aren't ready.

2024-01-16 19:09 UTC, jonator commented
Closing in favor of: https://github.com/osmosis-labs/osmosis-frontend/pull/2696

2024-01-16 19:09 UTC, closed without merging