Port & Implement Assets page (- ibc transfer)
osmosis-labs/osmosis-frontend pull request #297
Opened 2022-03-12 15:28 UTC by jonator

Closes: #242 

* Added the osmosis account at `@osmosis-labs/stores/assets` but did not add to root store at `root.ts`
  * Includes message composition code
* Refactored IBC transfer logic, but did not implement (due to problem above)
* Tweak some components, namely pool-card and search-box
* Wrapped some `@osmosis-labs/stores` objects with an observable mobx class: `ObservableAssets` (at `packages/web/stores/assets` 
  * Pros: globally accessible memoized calculations 
  * Cons: Organization/architecture doesn't seem fit. Was considering writing a hook with `useMemo` called `useUserAssets` or the like, but wouldn't get the pro above.

2022-03-15 16:12 UTC, delivan commented on packages/web/components/control/menu-dropdown.tsx
> +        key={nanoid()}
`nanoid` for React component's key is not recommended. Check out the [docs](https://github.com/ai/nanoid#react)

2022-03-15 16:13 UTC, delivan commented on packages/web/components/input/input-box.tsx
> +                key={nanoid()}
nanoid for React component's key is not recommended.

2022-03-22 01:29 UTC, jonator commented
Converting to draft to implement updated IBC transfer dialog design/UI

2022-03-23 00:58 UTC, jonator commented on packages/stores/package.json
> +    "@keplr-wallet/cosmos": "0.9.12-rc.0",
For some of the `@keplr-wallet/stores` imports I needed to use `^0.9.16` to avoid build errors.

2022-03-23 01:03 UTC, jonator commented on packages/stores/src/account/msg/make-msg.ts
> +        tokenIn: {
My goal with this is to keep primitive types to pass to the math package. That reduces the dependency on constructing these objects when not necessary. Also, `CoinPretty` doesn't expose amount as public (it's protected).

2022-03-23 01:06 UTC, jonator commented on packages/web/components/cards/pool-card.tsx
> +  const poolTitle =
We can wait until the pools PR is merged before merging this PR.

2022-03-23 01:14 UTC, jonator commented
This PR is blocked by PR #287.

2022-03-24 02:36 UTC, jonator commented
@delivan I merged to master and reconciled some conflicts. Notable files to review:
* packages/web/components/cards/pool-card.tsx
* packages/web/components/table/index.tsx
* packages/web/components/control/checkbox.tsx

Thanks!

2022-03-25 09:21 UTC, delivan reviewed
If I try to sort in order of network in sorting menu, I get the following error:
![스크린샷 2022-03-25 오후 5 57 35](https://user-images.githubusercontent.com/32129022/160091856-6d96a702-6955-42b1-bb87-dcaa800c5b72.png)

2022-03-25 09:35 UTC, delivan commented on packages/web/hooks/use-ibc-transfer/types.ts
> +/*
Remove the comments

2022-03-25 09:35 UTC, delivan commented on packages/web/modals/ibc-transfer.tsx
> +              onInput={(value) => {
Please allow to input dot for decimals

2022-03-25 09:35 UTC, delivan commented on packages/web/components/table/assets-table.tsx
> +          rowDefs={tableData.map(() => ({ makeHoverClass: () => " " }))}
It would be better to remove hover styling to make the user aware nothing happened if clicking table row.

2022-03-28 13:27 UTC, delivan requested changes

2022-03-28 13:27 UTC, delivan commented on packages/web/pages/assets/index.tsx
> +                    .computeMostAPY(poolId, priceStore)
How about using `maxDecimals(2)` to sync with pool card on pools page?

2022-03-28 18:42 UTC, jonator commented on packages/web/pages/assets/index.tsx
> +                  value: queriesOsmosis.queryIncentivizedPools
@osmosis-labs/data victor and I agree that the info site should replace the rotating OSMO logo with simple geometric placeholders. I think syncing design here would very much help with consistent branding across app and info.

<img width="387" alt="Screen Shot 2022-03-28 at 1 40 50 PM" src="https://user-images.githubusercontent.com/4606373/160464994-334a333a-2bba-42fd-8809-59c665abb968.png">

2022-03-28 21:24 UTC, jonator commented
Yet to do:

- [ ] Create additional custom withdrawal safeguard: [Figma](https://www.figma.com/proto/7iuO8MZeiYezTnF7suwTNN/draft-UI?page-id=106%3A6758&node-id=476%3A30575&viewport=332%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=476%3A30575)

2022-04-04 09:57 UTC, delivan commented
LGTM besides withdrawal safeguard 👍

2022-04-04 18:20 UTC, jonator commented
@delivan 

I've added the new store init logic here, and added the withdraw safeguard. Feel free to approve. 🚀

2022-04-05 13:30 UTC, delivan approved these changes

2022-04-05 15:52 UTC, merged