feat: Swap modal tab system
osmosis-labs/osmosis-frontend pull request #3284
Opened 2024-05-30 13:50 UTC by crnbarr93

## What is the purpose of the change:
These changes add a simple tab system for ths swap modal in order to allow options for placing limit orders. The tabs include three options:
1. Buy 
2. Sell
3. Swap

With the first and second options being specifically for limit orders and the 3rd being the current swap order implementation. These tabs currently don't alter the swap modal in any way but are set up to allow a parent component to record and update state depending on the tab selected.

### Linear Task

TODO

## Brief Changelog
- Added `SwapToolTabs` component
- Added `activeTab` state to `SwapTool`

## Testing and Verifying
No unit-tests or integration tests were written for this component

2024-05-31 13:15 UTC, fabryscript requested changes
I think there is no need to re-invent the wheel for the tabs system

Here is a good alternative with helper styles: https://headlessui.com/react/tabs

2024-05-31 13:18 UTC, fabryscript requested changes

2024-05-31 13:18 UTC, fabryscript commented on packages/web/components/swap-tool/swap-tool-tabs.tsx
> +            "text-subtitle6 justify-center rounded-[16px] border-2 py-[12px] text-center font-subtitle1 transition-all duration-75",
you can use `py-3` and `rounded-2xl`

2024-05-31 13:18 UTC, fabryscript commented on packages/web/components/swap-tool/swap-tool-tabs.tsx
> +    <div className="grid grid-cols-3 rounded-[16px] bg-osmoverse-900 transition-opacity">
you can use `rounded-2xl`

2024-05-31 16:25 UTC, jonator reviewed
It seems the designs are very much still in flux that are quite different from this implementation.

Should we hold of or close this until designs are finalized.

Was inspired by this:
https://osmosis-network.slack.com/archives/C06PW1BHKC3/p1717172538599349

2024-06-02 14:13 UTC, crnbarr93 commented
> It seems the designs are very much still in flux that are quite different from this implementation.
> 
> Should we hold of or close this until designs are finalized.
> 
> Was inspired by this: https://osmosis-network.slack.com/archives/C06PW1BHKC3/p1717172538599349

Happy to hold off on this PR until designs are finalized.

2024-06-02 14:13 UTC, closed without merging