Bridge Providers: remove `sourceDenom`
osmosis-labs/osmosis-frontend pull request #3389
Opened 2024-06-20 22:00 UTC by jonator

## What is the purpose of the change:

Simplifies bridge providers by only using `address` as the primary asset identifier, instead of also having `sourceDenom`. This is made possible by the providers' recent usage of their own asset and chain lists for providing a selectable list of assets and chains to the user. This makes the providers simpler, easier to use, and easier to maintain. Further, we were able to remove some usage of our hardcoded Axelar asset list, which effectively hides the Axelar-specific complexity of their use of their own asset identifiers.

### Linear Task

[Linear Task URL](https://linear.app/osmosis/issue/FE-573/bridge-providers-remove-sourcedenom)

## Brief Changelog

* Remove `sourceDenom` from bridge interface
* Adapt Axelar bridge provider to use it's chain and assets API for finding Axelar asset IDs for use with it's APIs. This greatly simplifies usage of the Axelar bridge provider and helps contain it's identifier complexity.
* Re-enable withdraws with Squid bridge provider
* Fixed a few UI bugs with bridge transfer v2 (invalid useQuery query ID param with ERC20 balance query, invalid ICNS queries with EVM addresses)
* Adapted the `getAssetPrice` function to also accept chain IDs and origin asset denoms to help increase the chance of getting Osmosis prices for assets on other chains (TODO: provide CoinGecko IDs and fall back to that)

## Testing and Verifying

* All tests pass
* Existing v2 bridge flows are working

2024-06-25 21:51 UTC, JoseRFelix requested changes
LGTM! There's a stray console log

2024-06-25 21:51 UTC, JoseRFelix commented on packages/web/modals/bridge-transfer-v2.tsx
> +  });
Stray console log

2024-06-26 12:22 UTC, CryptoAssassin1 approved these changes

2024-06-26 15:06 UTC, kamal-sutra approved these changes

2024-06-26 15:30 UTC, JoseRFelix approved these changes
LGTM!

2024-06-26 15:37 UTC, merged