(Deposit/Withdraw) Support connection error transfer status in transfer UI
osmosis-labs/osmosis-frontend pull request #3455
Opened 2024-07-05 18:57 UTC by jonator

## What is the purpose of the change:

### Linear Task

[Linear Task URL](https://linear.app/osmosis/issue/FE-622/support-connection-error-transfer-status-in-transfer-ui)

## Brief Changelog

* Migrate to transfer status type from bridge package in UI, adapt to legacy IBC transfer status history store
* Minor cleanup of interchain balances tRPC query

## Testing and Verifying

Transfer statuses are visible in table, including connection error types

2024-07-05 20:18 UTC, JoseRFelix requested changes

2024-07-05 20:56 UTC, jonator commented on packages/web/components/swap-tool/__tests__/swap-tool.spec.tsx
> -/* eslint-disable import/no-extraneous-dependencies */
It started flaking

2024-07-06 17:40 UTC, JoseRFelix commented on packages/web/components/swap-tool/__tests__/swap-tool.spec.tsx
> -/* eslint-disable import/no-extraneous-dependencies */
This test is quite important as it's a smoke test for our swap tool and has helped me identify errors in the past. Do you know which assertion is failing so I can take a look?

2024-07-06 19:43 UTC, jonator commented on packages/web/components/swap-tool/__tests__/swap-tool.spec.tsx
> -/* eslint-disable import/no-extraneous-dependencies */
It was failing on assertion at line 195. What's strange, is sometimes the GitHub action tests succeeds and it fails locally on the same branch. Also, why are pools being queried? It should be using SQS now for quotes.

2024-07-06 19:44 UTC, jonator commented
@JoseRFelix what's the plan with fixing the swap tool test? It's worth noting that this is getting replaced by new trade flow very soon as well.

2024-07-08 16:09 UTC, JoseRFelix commented
@jonator I approved the PR. By the way, the build is failing because the chainlist added an unexpected property. @JeremyParish69 is working on it

2024-07-08 17:01 UTC, merged