(1CT) Exclude other fee tokens for 1CT transactions
osmosis-labs/osmosis-frontend pull request #3521
Opened 2024-07-15 21:26 UTC by JoseRFelix

## What is the purpose of the change:

There's an unexpected error coming from the chain when using other fee tokens while broadcasting a 1CT transaction. We've identified this as an issue on the chain that will be resolved in v26. As a temporary measure, we'll exclude alternate fee tokens. However, our current gas estimation logic doesn't prioritize OSMO over other tokens, which means we'll consistently get tokens other than OSMO. If we enable onlyDefaultFeeDenom, we'll get OSMO as a fee token, but this doesn't mean we want to exclude other tokens entirely. We still want them as a fallback for wallet signing, so we can't use that setting. Therefore, we need to update our gas logic to support this case

### Linear Task

[Linear Task URL](https://linear.app/osmosis/issue/FE-782/exclude-other-fee-tokens-for-1ct-transactions)

## Brief Changelog

- Excludes fee tokens from 1CT transactions
- Prioritize OSMO to pay gas

## Testing and Verifying

- [ ] Can perform 1CT txs without unexpected errors

2024-07-15 21:31 UTC, jonator requested changes

2024-07-15 21:31 UTC, jonator commented on packages/tx/src/gas.ts
Let's make sure tests are updated to account for these changes in picking of fee tokens

2024-07-15 22:01 UTC, CryptoAssassin1 approved these changes

2024-07-16 05:07 UTC, kamal-sutra approved these changes

2024-07-16 08:37 UTC, PaddyMc approved these changes
Ace, ty

2024-07-16 16:05 UTC, merged