feat: added gas fee esimate to place limit state
osmosis-labs/osmosis-frontend pull request #3584
Opened 2024-07-23 15:34 UTC by crnbarr93

## What is the purpose of the change:
These changes add a gas fee estimate to the `usePlaceLimit` hook.

### Linear Task

[LIM-199: Review Limit/Market Modal](https://linear.app/osmosis/issue/LIM-199/[redesign]-review-limitmarket-modal)

## Brief Changelog
- Added new `gas` field to `usePlaceLimit`

2024-07-24 14:10 UTC, fabryscript approved these changes

2024-07-24 14:51 UTC, jonator commented on packages/web/hooks/limit-orders/use-place-limit.ts
> +import { cosmwasmMsgOpts } from "@osmosis-labs/stores";
Generally we consider stores package to be deprecated. Were trying to move msg/tx related logic to tx package. I'm moving them in `jonator/fixes` branch

2024-07-24 17:14 UTC, jonator commented on packages/web/hooks/limit-orders/use-place-limit.ts
> +import { cosmwasmMsgOpts } from "@osmosis-labs/stores";
Just merged to stage

2024-07-24 17:15 UTC, jonator requested changes

2024-07-24 17:15 UTC, jonator commented on packages/web/hooks/limit-orders/use-place-limit.ts
> +import { cosmwasmMsgOpts } from "@osmosis-labs/stores";
Just merged this move to stage, pls update imports (and anywhere else you import this from)

Can just change it from /stores to /tx

2024-07-31 10:59 UTC, fabryscript approved these changes

2024-07-31 11:04 UTC, merged