Add Transmuter Contract Codes
osmosis-labs/osmosis-frontend pull request #3749
Opened 2024-08-16 16:47 UTC by JohnnyWyles

Adding the 3 other contract uploads for Transmuter pools so that these can be filtered out in the pools list if wanted.

Transmuter 1.0 already listed
Transmuter 2.0 was never instantiated
This adds 3.0, 3.1 and 3.2 which are the alloyed asset pools - but also are transmuters and often dominate the volume charts.

2024-10-08 03:26 UTC, jonator requested changes
I believe this is connected to legacy query code.

It's preferred to use this now:

https://github.com/osmosis-labs/osmosis-frontend/blob/2291cffffb5f5ef2a41ad747bd51ae6072a2becd/packages/server/src/queries/complex/pools/env.ts#L4

2024-10-11 18:53 UTC, jonator approved these changes

2024-10-11 18:54 UTC, jonator reviewed
@JohnnyWyles if we could add `// @deprecated use packages/server/src/queries/complex/pools/env.ts` comment above the old one, that would help prevent this confusion in the future

2024-10-15 17:09 UTC, MaxMillington commented
@JohnnyWyles is there any update on this? need any help?

2024-10-16 11:11 UTC, JohnnyWyles commented
> @JohnnyWyles is there any update on this? need any help?

I think I did the change that Jon requested?
Not sure what's missing from this

2024-11-25 10:22 UTC, JohnnyWyles commented
Please let me know what I'm missing here - I added a comment and the new code IDs to the alternative location as recommended

2024-12-12 11:02 UTC, EnricoBarbieri1997 approved these changes

2024-12-12 11:12 UTC, DavideSegullo approved these changes

2024-12-12 11:32 UTC, merged