Canto
osmosis-labs/osmosis-frontend pull request #743
Opened 2022-08-20 16:57 UTC by sunnya97

2022-08-24 19:54 UTC, JeremyParish69 commented
still needs ibc channel numbers

2022-10-05 19:35 UTC, ankurdotb requested changes

2022-10-05 19:35 UTC, ankurdotb commented on packages/web/config/chain-infos.ts
> +      rest: "http://164.90.154.41:1317",
Not mandatory but you'd be better off mapping this to a DNS record so that if the IP address rotates, you don't need to file a PR again.

2022-10-17 15:53 UTC, jonator commented
@JeremyParish69 updates on this?

2022-11-02 20:00 UTC, jonator commented
Closing as stale, can be reopened as needed

2022-11-02 20:00 UTC, closed without merging