Enable GKEY coinGeckoId
osmosis-labs/osmosis-frontend pull request #808
Opened 2022-09-20 01:44 UTC by Rizbe

2022-09-22 20:34 UTC, JeremyParish69 commented on packages/web/config/chain-infos.ts
> +          coinGeckoId: "pool:gkey",
this id is not defined (but you can do so in /config/price.ts). No point in uncommenting this without it defined.

2022-09-22 20:35 UTC, JeremyParish69 requested changes
please first define this id

2022-09-23 14:23 UTC, Rizbe commented
Updated the PR

I assume once this is merged we will get gkey price data using: https://api-osmosis.imperator.co/tokens/v2/price/gkey 

Currently it says: `{"message":"Oops! Something went wrong with gkey ..."}`

2022-09-24 05:58 UTC, JeremyParish69 approved these changes
LGTM

2022-09-24 18:51 UTC, merged