Add Gravity Externals
osmosis-labs/osmosis-frontend pull request #918
Opened 2022-10-23 21:28 UTC by JohnnyWyles

As per Proposal 347 https://www.mintscan.io/osmosis/proposals/347 Will go live Epoch of 24th October.

2022-10-24 22:13 UTC, JeremyParish69 reviewed
There are already objects for 633 and 625, so those should be modified rather than creating new ones. In addition, would be nice to keep pool numbers in order

2022-10-24 22:13 UTC, JeremyParish69 requested changes
There are already objects for 633 and 625, so those should be modified rather than creating new ones. In addition, would be nice to keep pool numbers in order

2022-10-25 07:51 UTC, JohnnyWyles commented
> There are already objects for 633 and 625, so those should be modified rather than creating new ones. In addition, would be nice to keep pool numbers in order

Didn't realise they had previous incentives sorry, replaced these objects.
Was also going by Gauge order, will do pool order in future

2022-10-25 21:11 UTC, JeremyParish69 approved these changes

2022-10-25 21:24 UTC, merged