Update ko.json
osmosis-labs/osmosis-frontend pull request #971
Opened 2022-11-07 20:09 UTC by dogemos

Modify some words for better flow

2022-11-07 23:38 UTC, jonator requested changes

2022-11-07 23:38 UTC, jonator commented on packages/web/localizations/ko.json
> +      "poolId": id}"
Please add pool id here

2022-11-09 01:48 UTC, jonator commented
@dogemos please remerge as well to get new korean translations

2022-11-15 16:33 UTC, jonator approved these changes

2022-11-15 16:33 UTC, merged

2022-11-18 12:23 UTC, gnujoow commented
@dogemos I've just checked the PR. the flow even better than as it was.